version: 2.1
orbs:
  node: circleci/node@2.1.1
jobs:
  build-and-test-COLONY:
    executor:
      name: node/default
      tag: '10.20'
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get update && sudo apt-get install python3.6
      - run: yarn bootstrap
      - run: npx truffle obtain --solc=0.5.16
      - run: COLONY=true yarn ci

workflows:
  colony:
    jobs:
      - build-and-test-COLONY
